version: '3'
services:

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: modutime
      MYSQL_ROOT_PASSWORD:
    expose:
      - 3306
    ports:
      - 3306:3306

  web:
    container_name: web
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/modutime
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
