spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
        oauth2: TRACE
        security.oauth2.client.web: TRACE

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: TRACE
        security.oauth2.client.web: TRACE
