spring:
  profiles:
    active: local
    include:
      - db
      - oauth2
      - host
      - security
      - logging
      - sentry

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  endpoint:
    health:
      show-details: never
