spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/modutime?serverTimezone=Asia/Seoul
    username: root
    password:
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
